version: "3.9"
services:

  db:
    container_name: "CryptoProjDatabase"
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cryptoproj
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: "CryptoProjApp"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/appuser
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  db_data: