"""3

Revision ID: c5c5d573cd66
Revises: ec6f2e88fceb
Create Date: 2024-05-15 16:38:00.941934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5c5d573cd66"
down_revision: Union[str, None] = "ec6f2e88fceb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract", "erc20_version", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract", "erc20_version", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
